<?php

// backend/app/Models/Sale.php
// Purpose: Repersents a customer transaction recorded at the POS terminal.

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Sale extends Model
{
    protected $table = 'sales';

    protected $fillable = [
        'uuid',
        'shop_id',
        'user_id',
        'receipt_number',
        'subtotal',
        'discount_amount',
        'tax_amount',
        'total_amount',
        'amount_paid',
        'change_amount',
        'payment_method',
        'mpesa_reference',
        'status',
        'notes',
        'sold_at',
        'synced_at',
    ];

    protected $casts = [
        'subtotal' => 'float',
        'discount_amount' => 'float',
        'tax_amount' => 'float',
        'total_amount' => 'float',
        'amount_paid' => 'float',
        'change_amount' => 'float',
        'sold_at' => 'datetime',
        'synced_at' => 'datetime',
    ];

    /**
     * Boot model events - auto-generates client-safe UUID and serial receipt number.
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($sale) {
            if (empty($sale->uuid)) {
                $sale->uuid = (string) Str::uuid();
            }
            if (empty($sale->receipt_number)) {
                $sale->receipt_number = self::generateReceiptNumber();
            }
        });
    }

    /**
     * Generate collision-free receipt number using PostgreSQL sequence.
     * Replaces the old row-count method that was prone to race conditions.
     */
    public static function generateReceiptNumber(): string
    {
        $year = Carbon::now()->year;
        $sequence = \Illuminate\Support\Facades\DB::selectOne(
            "SELECT nextval('receipt_sequence') AS seq"
        )->seq;
        return sprintf('SK-%d-%06d', $year, $sequence);
    }

    /**
     * Scope query to a specific date range.
     */
    public function scopeForDateRange(Builder $query, string $from, string $to): Builder
    {
        return $query->whereBetween('sold_at', [
            Carbon::parse($from)->startOfDay(),
            Carbon::parse($to)->endOfDay(),
        ]);
    }

    /**
     * Scope query to filter by payment methods.
     */
    public function scopeByPaymentMethod(Builder $query, string $method): Builder
    {
        return $query->where('payment_method', $method);
    }

    /**
     * Scope query to a specific shop.
     */
    public function scopeForShop(Builder $query, int $shopId): Builder
    {
        return $query->where('shop_id', $shopId);
    }

    /**
     * Calculate absolute gross profit margin generated by this sale transaction.
     */
    public function profit(): float
    {
        $cost = $this->items->sum(function ($item) {
            return $item->buying_price * $item->quantity;
        });

        return max(0.00, $this->total_amount - $cost);
    }

    /**
     * Get the shop related to this sale.
     */
    public function shop(): BelongsTo
    {
        return $this->belongsTo(Shop::class, 'shop_id');
    }

    /**
     * Get the cashier user.
     */
    public function cashier(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Get all transaction items purchased.
     */
    public function items(): HasMany
    {
        return $this->hasMany(SaleItem::class, 'sale_id');
    }
}
